# Site settings
title: Liberty X
email: Liberty-x@bookings.com
description: > # this means to ignore newlines until "baseurl:"
  Part time developers, part time tribute band to the greats. We sing, we code, Liberty X 4lyf. Enjoy our page... Just a little bit
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: founderscoders
github_username:  liberty-x

# Build settings
markdown: kramdown
